#!/bin/sh
#

load_drivers()
{
	while IFS= read -r line; do
		modprobe $line
	done < "/etc/modules-load.myir/$1.conf"
}

do_board()
{
    mount -t jffs2 mtd:NAND.userdata /opt
    mkdir -p /home/ftp/nand
    mkdir -p /home/ftp/ram
    mkdir -p /tmp/myir
    mount -o bind /tmp/myir  /home/ftp/ram
    chmod -R 777 /home/ftp

	load_drivers "am335x" 
}

dmesg -n 5

case "$1" in
	start)
		do_board
		;;
	stop)
		;;
	restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
