#!/bin/sh
#

case "$1" in
  start)
    /usr/bin/psplash-write "PROGRESS 100"	
	/etc/modules-load.myir/postboot
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
