#! /bin/sh

MODEL=c335x

if grep "C335X" /sys/firmware/devicetree/base/model > /dev/null;then
	MODEL=c335x
fi
if grep "Y335X" /sys/firmware/devicetree/base/model > /dev/null;then
	MODEL=y335x
fi
if grep "J335X" /sys/firmware/devicetree/base/model > /dev/null;then
	MODEL=j335x
fi

if grep "updatesys_from_usbmsc_to_emmc" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE FROM USBMSC TO EMMC *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys.sh loader2emmc usbmsc $MODEL
fi
if grep "updatesys_from_sd_to_emmc" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE FROM SDCARD TO EMMC *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys.sh loader2emmc sd $MODEL
fi
#! /bin/sh
if grep "updatesys_from_usbmsc_to_nand" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE FROM USBMSC TO NAND *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys.sh loader2nand usbmsc $MODEL
fi
if grep "updatesys2_from_usbmsc_to_nand" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE with DUALBACKUP FROM USBMSC TO NAND *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys2.sh loader2nand usbmsc $MODEL
fi
if grep "updatesys_from_sd_to_nand" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE FROM SDCARD TO NAND *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys.sh loader2nand sd $MODEL
fi
if grep "updatesys2_from_sd_to_nand" /proc/cmdline > /dev/null;then
	echo
	echo "***********************************************"
	echo  $MODEL :"*** SYSTEM UPDATE with DUALBACKUP FROM SDCARD TO NAND *********"
	echo "***********************************************"
	echo
	yes | /etc/modules-load.myir/updatesys2.sh loader2nand sd $MODEL
fi
if grep "io_test" /proc/cmdline > /dev/null;then
        echo
        echo "***********************************************"
        echo $MODEL: "*************    IO TEST    *************"
        echo "***********************************************"
        echo
        /usr/bin/pcba_test -a &
fi
