#!/bin/sh
/usr/bin/psplash &

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue
	/usr/bin/psplash-write "PROGRESS $(echo "$i" | cut -c 14-15)"	
     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

/usr/bin/psplash-write "PROGRESS 100"