#!/bin/sh

python /usr/share/myir/www/init_boardcfg.py

if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
	eval `dbus-launch --sh-syntax`
	echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi
export DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS"

#sleep 5
#MAC=$(ifconfig eth0|grep eth0|awk '{print $5}' | sed 's/://g' | tr '[A-Z]' '[a-z]')
#connmanctl config "ethernet_"$MAC"_cable" --ipv4 manual 192.168.1.100 255.255.255.0 192.168.1.1

/home/myir/mxbackend &
python /usr/share/myir/www/server.py &

TS_CALIBRATION_FILE=/etc/pointercal
if [ ! -f $TS_CALIBRATION_FILE ];then
        export TSLIB_TSDEVICE=/dev/input/touchscreen0
        ts_calibrate 
fi
/home/myir/mxapp --platform linuxfb &


